language: perl
perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
    - git config --global user.name "TravisCI"
    - git config user.email 'travis@nowhere.dne'

install:
    - cpanm --verbose Test::TCP
    - cpanm --installdeps .

script:
    # test server
    - prove -Ilib t
    # test client (TODO)

env: RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
