language: perl
perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
    - git config --global user.name "TravisCI"
    - git config user.email 'travis@nowhere.dne'

install:
    - cpanm --notest Net::Server # failed test in 2.007
    - cpanm --installdeps .

script:
    # test server
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1
    - prove -Ilib t
    # test client (TODO)
