charset: UTF-8
serializer: JSON
engines:
    template_toolkit:
        ENCODING: utf8

title: Cocoda Server
version: 0.0.1

port: 6006

terminologies:
    - DDC
    - RVK:
        key: rvk
    - +Cocoda::Terminology::BK
