engines:
    JSON:
        utf8: '0'
        pretty: '1'

title: Cocoda Server
version: 0.0.4
profile: '../profile'

terminologies:
    - DDC
    - RVK:
        key: rvk
    - +Cocoda::Terminology::BK
    - GNDSubjects
